### ISSUE TITLE
请问能否优化常驻通知，或筛选/隐藏指定APP的常驻通知

### ISSUE THREAD

**Issue by wwjjhh1995** [wenyi401/IsleNotify#1]
在HyperOS中，若有常驻通知（如Clash的运行状态通知条），会持续触发灵动脑门。

不知是否有优化解决方法？

https://github.com/wenyi401/IsleNotify/assets/41428076/07a8e4f3-6987-46fe-a5f8-ca8af1e8051a

**Comment by wenyi401** [comment]
只需要在自定义中屏蔽通知，然后保存重启系统界面即可

**Comment by bwmgd** [comment]
> 只需要在自定义中屏蔽通知，然后保存重启系统界面即可

但是有些下载进度类的通知不包含关键词, 难以进行匹配, 建议可以通过渠道进行屏蔽
